### ISSUE TITLE
Exception when parsing Enum with fields

### ISSUE THREAD

**Issue by kronar** [paul-hammant/qdox#1]
The parser throws exception when tries to parse enum with fields.
I've created small project that reproduces this issue.
https://github.com/kronar/qdox-bug

**Comment by rfscholte** [comment]
I've been searching through the Official Java Language Specification and it seems like the documentation isn't complete on this part: https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-EnumConstant describes how it should look like, but the arguments doesn't bring me to the methodInvocation. I'll try to get the draft for Java9, since it'll introduce modules. Hopefully they've added it, otherwise I'll ask them for the details.

**Comment by pofuk** [comment]
I also have same problem. Which part is not documented?

> An enum constant may be followed by arguments, which are passed to the constructor of the enum when the constant is created during class initialization as described later in this section. The constructor to be invoked is chosen using the normal rules of overload resolution (§15.12.2). If the arguments are omitted, an empty argument list is assumed.
